name: jasonodonnell
favicon: null
layout_spectrum: 0.6014631825964898
typography_spectrum: 0.5527782107237726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8405835789162666
  lightness: 0.002506634220480919
  saturation: 0.9614963647909462
  rhythmicContrast: 0.2492978684604168
purpose: []
